'use client';

import { useEffect, useState } from 'react';
import {
  PageHero,
  Card,
  Section,
  Eyebrow,
  Chip,
  PrimaryButton,
  GhostButton,
  EmptyState,
  CREAM,
  CREAM_DIM,
  CREAM_MUTED,
  SIGNAL,
  AMBER,
  BG_CARD,
  LINE,
  LINE2,
  DISPLAY_FONT,
  MONO_FONT,
  ERR,
} from '@/lib/brand';

interface PendingAssignment {
  canonical_slug: string;
  canonical_id: string | null;
  business_name: string;
  vertical: string | null;
  postcode: string | null;
  latest_demo_at: string;
  latest_artefact_id: string;
  demo_count: number;
  demo_size_kb: number;
  photo_count: number;
  aesthetic_positioning: string | null;
  dominant_hex: string | null;
  latest_brief_id: string | null;
  diagnosis: string | null;
  pitch_angle: string | null;
  google_rating: number | null;
  google_review_count: number | null;
  instagram_handle: string | null;
  latest_pitch_brief_id: string | null;
  hook: string | null;
  contact_name: string | null;
  qa_score: number | null;
  qa_passed: boolean | null;
}

interface PendingResponse {
  pending: PendingAssignment[];
  total: number;
  queried_at: string;
}

interface SalesUser {
  id: string;
  name: string;
  area_postcode: string | null;
  active: boolean;
}

interface AssignSuccess {
  slug: string;
  user_name: string;
  business_name: string;
  demo_site_domain: string | null;
}

const NERVE_BASE_URL = 'https://nerve.salespatch.co.uk';

export default function AdminQueuePage() {
  const [data, setData] = useState<PendingResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [verticalFilter, setVerticalFilter] = useState('');
  const [team, setTeam] = useState<SalesUser[]>([]);
  const [recentSuccess, setRecentSuccess] = useState<AssignSuccess | null>(null);

  useEffect(() => {
    loadQueue();
  }, [verticalFilter]);

  useEffect(() => {
    loadTeam();
  }, []);

  async function loadQueue() {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams();
      if (verticalFilter) params.set('vertical', verticalFilter);
      const res = await fetch(`/api/admin/queue?${params}`);
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? `HTTP ${res.status}`);
      }
      const json = (await res.json()) as PendingResponse;
      setData(json);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }

  async function loadTeam() {
    try {
      const res = await fetch('/api/admin/salespeople');
      if (!res.ok) return;
      const body = (await res.json()) as { data: SalesUser[] };
      setTeam((body.data ?? []).filter((u) => u.active));
    } catch {
      // Non-fatal — picker stays empty.
    }
  }

  async function handleAssigned(success: AssignSuccess) {
    setRecentSuccess(success);
    await Promise.all([loadQueue(), loadTeam()]);
    setTimeout(() => setRecentSuccess((curr) => (curr === success ? null : curr)), 6000);
  }

  const verticals = Array.from(
    new Set((data?.pending ?? []).map((p) => p.vertical).filter((v): v is string => !!v)),
  ).sort();

  return (
    <div className="py-10">
      <PageHero
        eyebrow="Queue"
        title="NERVE-built leads,"
        accent="ready to assign."
        sub="Demos generated by /build-demo in Claude Code. Pick a contractor, click Assign — the lead lands in their dashboard with the demo URL, pitch brief and contact details already populated."
        right={
          <GhostButton size="sm" onClick={loadQueue}>
            {loading ? 'Refreshing…' : 'Refresh'}
          </GhostButton>
        }
      />

      {/* Header sub-stamp */}
      {data && (
        <div
          className="text-[11px] uppercase mb-6"
          style={{ fontFamily: MONO_FONT, letterSpacing: '0.14em', color: CREAM_MUTED }}
        >
          {data.total} pending · queried {formatTime(data.queried_at)}
        </div>
      )}

      {/* Success banner */}
      {recentSuccess && (
        <Card padding="md" accent className="mb-5">
          <div className="flex items-start justify-between gap-4">
            <div>
              <Eyebrow accent>Imported</Eyebrow>
              <p className="text-[15px] m-0" style={{ color: CREAM }}>
                {recentSuccess.business_name} → {recentSuccess.user_name}
              </p>
            </div>
            {recentSuccess.demo_site_domain && (
              <a
                href={recentSuccess.demo_site_domain}
                target="_blank"
                rel="noreferrer"
                className="text-[12px] no-underline whitespace-nowrap"
                style={{ color: SIGNAL, fontFamily: MONO_FONT, letterSpacing: '0.04em' }}
              >
                Open demo →
              </a>
            )}
          </div>
        </Card>
      )}

      {/* Vertical filter chips */}
      {verticals.length > 0 && (
        <div className="flex flex-wrap gap-2 mb-6">
          <Chip
            active={verticalFilter === ''}
            onClick={() => setVerticalFilter('')}
            count={data?.total ?? 0}
          >
            All
          </Chip>
          {verticals.map((v) => (
            <Chip
              key={v}
              active={verticalFilter === v}
              onClick={() => setVerticalFilter(v)}
            >
              {capitalise(v)}
            </Chip>
          ))}
        </div>
      )}

      {/* Error */}
      {error && (
        <Card padding="md" className="mb-5" style={{ borderColor: 'rgb(255 138 128 / 0.35)' }}>
          <Eyebrow>Queue read failed</Eyebrow>
          <p className="text-[12px] m-0" style={{ color: ERR, fontFamily: MONO_FONT }}>
            {error}
          </p>
        </Card>
      )}

      {/* Empty */}
      {data && data.pending.length === 0 && !error && (
        <EmptyState
          eyebrow="Clear"
          title="Queue is empty."
          sub="Every NERVE-built lead has been assigned. Run /build-demo on a new lead in Claude Code and refresh — it appears here within seconds."
        />
      )}

      {/* Cards */}
      {data && data.pending.length > 0 && (
        <div className="grid gap-4">
          {data.pending.map((card) => (
            <QueueCard
              key={card.canonical_slug}
              card={card}
              team={team}
              onAssigned={handleAssigned}
            />
          ))}
        </div>
      )}

      {loading && !data && (
        <p className="text-[13px] text-center py-12 m-0" style={{ color: CREAM_MUTED }}>
          Loading queue…
        </p>
      )}
    </div>
  );
}

interface QueueCardProps {
  card: PendingAssignment;
  team: SalesUser[];
  onAssigned: (s: AssignSuccess) => void | Promise<void>;
}

function QueueCard({ card, team, onAssigned }: QueueCardProps) {
  const [selectedUserId, setSelectedUserId] = useState('');
  const [assigning, setAssigning] = useState(false);
  const [cardError, setCardError] = useState<string | null>(null);

  const demoExternalUrl = `${NERVE_BASE_URL}/api/public/demo/${encodeURIComponent(card.canonical_slug)}`;

  async function handleAssign() {
    if (!selectedUserId) return;
    setAssigning(true);
    setCardError(null);
    try {
      const res = await fetch('/api/admin/import-from-nerve', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ slug: card.canonical_slug, user_id: selectedUserId }),
      });
      const body = (await res.json().catch(() => ({}))) as {
        data?: {
          user_name: string;
          business_name: string;
          demo_site_domain: string | null;
        };
        error?: string;
      };
      if (!res.ok) {
        throw new Error(body.error ?? `HTTP ${res.status}`);
      }
      if (body.data) {
        await onAssigned({
          slug: card.canonical_slug,
          user_name: body.data.user_name,
          business_name: body.data.business_name,
          demo_site_domain: body.data.demo_site_domain,
        });
      }
    } catch (err) {
      setCardError(err instanceof Error ? err.message : String(err));
    } finally {
      setAssigning(false);
    }
  }

  return (
    <Card padding="md">
      <div className="flex items-start gap-5">
        {/* Brand swatch */}
        <div className="shrink-0 flex flex-col items-center gap-1.5 pt-1">
          <div
            className="w-12 h-12 rounded-xl"
            style={{
              backgroundColor: card.dominant_hex ?? BG_CARD,
              border: `1px solid ${LINE}`,
            }}
            title={card.dominant_hex ?? 'no brand colour'}
          />
          {card.dominant_hex && (
            <span
              className="text-[9px]"
              style={{ color: CREAM_MUTED, fontFamily: MONO_FONT }}
            >
              {card.dominant_hex}
            </span>
          )}
        </div>

        {/* Main info */}
        <div className="flex-1 min-w-0">
          <div className="flex items-start justify-between gap-4 mb-2">
            <div className="min-w-0">
              <div className="flex items-baseline gap-3 flex-wrap">
                <h3
                  className="text-[18px] m-0 truncate"
                  style={{
                    fontFamily: DISPLAY_FONT,
                    color: CREAM,
                    fontWeight: 500,
                    letterSpacing: '-0.015em',
                  }}
                >
                  {card.business_name}
                </h3>
                <span
                  className="text-[11px] shrink-0"
                  style={{ color: CREAM_MUTED, fontFamily: MONO_FONT, letterSpacing: '0.04em' }}
                >
                  {card.canonical_slug}
                </span>
                <a
                  href={demoExternalUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="text-[11px] no-underline shrink-0"
                  style={{ color: SIGNAL, fontFamily: MONO_FONT, letterSpacing: '0.04em' }}
                  title="Open demo in new tab"
                >
                  open demo ↗
                </a>
              </div>
              <div
                className="text-[12px] mt-1.5 flex items-center gap-2 flex-wrap"
                style={{ color: CREAM_DIM, fontFamily: MONO_FONT, letterSpacing: '0.04em' }}
              >
                {card.vertical && <span>{card.vertical.toUpperCase()}</span>}
                {card.postcode && (
                  <>
                    <span style={{ color: CREAM_MUTED }}>·</span>
                    <span>{card.postcode}</span>
                  </>
                )}
                {card.instagram_handle && (
                  <>
                    <span style={{ color: CREAM_MUTED }}>·</span>
                    <span>@{card.instagram_handle}</span>
                  </>
                )}
                {card.google_rating !== null && (
                  <>
                    <span style={{ color: CREAM_MUTED }}>·</span>
                    <span>
                      ★ {card.google_rating.toFixed(1)}
                      {card.google_review_count !== null && ` (${card.google_review_count})`}
                    </span>
                  </>
                )}
              </div>
            </div>

            {/* Badges */}
            <div className="flex items-center gap-2 shrink-0">
              {card.qa_score !== null && (
                <Pill
                  label={`QA ${card.qa_score}`}
                  tone={card.qa_passed ? 'signal' : 'amber'}
                  title={card.qa_passed ? 'QA pass' : 'QA fail'}
                />
              )}
              <Pill
                label={card.canonical_id ? 'canonical' : 'slug only'}
                tone={card.canonical_id ? 'muted' : 'amber'}
                title={
                  card.canonical_id
                    ? `BusinessIdentity ${card.canonical_id}`
                    : 'No F1 BusinessIdentity row — pre-F1 producer ingest or backfill not run'
                }
              />
            </div>
          </div>

          {/* Pitch angle */}
          {(card.pitch_angle || card.hook || card.diagnosis) && (
            <p
              className="text-[13.5px] m-0 mb-3"
              style={{ color: CREAM_DIM, lineHeight: 1.55 }}
            >
              {card.pitch_angle ?? card.hook ?? card.diagnosis}
            </p>
          )}

          {/* Demo metadata */}
          <div
            className="flex items-center gap-3 text-[11px]"
            style={{ color: CREAM_MUTED, fontFamily: MONO_FONT, letterSpacing: '0.04em' }}
          >
            <span>{card.photo_count} photo{card.photo_count === 1 ? '' : 's'}</span>
            <span>·</span>
            <span>{card.demo_size_kb.toLocaleString()}kb</span>
            {card.demo_count > 1 && (
              <>
                <span>·</span>
                <span>{card.demo_count} versions</span>
              </>
            )}
            <span>·</span>
            <span>built {formatTime(card.latest_demo_at)}</span>
            {card.aesthetic_positioning && (
              <>
                <span>·</span>
                <span className="truncate italic" title={card.aesthetic_positioning}>
                  {card.aesthetic_positioning}
                </span>
              </>
            )}
          </div>

          {cardError && (
            <p
              className="text-[12px] mt-3 m-0"
              style={{ color: ERR, fontFamily: MONO_FONT }}
            >
              {cardError}
            </p>
          )}
        </div>

        {/* SP picker + Assign button */}
        <div className="shrink-0 flex flex-col gap-2 w-[220px]">
          <select
            value={selectedUserId}
            onChange={(e) => setSelectedUserId(e.target.value)}
            disabled={assigning || team.length === 0}
            className="w-full px-3 py-2.5 rounded-full text-[13px]"
            style={{
              background: BG_CARD,
              color: CREAM,
              border: `1px solid ${LINE}`,
              fontFamily: DISPLAY_FONT,
              cursor: assigning || team.length === 0 ? 'not-allowed' : 'pointer',
              opacity: assigning || team.length === 0 ? 0.5 : 1,
            }}
          >
            <option value="">{team.length === 0 ? 'No active contractors' : 'Pick contractor…'}</option>
            {team.map((u) => (
              <option key={u.id} value={u.id} style={{ background: BG_CARD, color: CREAM }}>
                {u.name}
                {u.area_postcode ? ` · ${u.area_postcode}` : ''}
              </option>
            ))}
          </select>
          <PrimaryButton
            onClick={handleAssign}
            disabled={!selectedUserId || assigning}
            size="sm"
          >
            {assigning ? 'Importing…' : 'Assign'}
          </PrimaryButton>
        </div>
      </div>
    </Card>
  );
}

function Pill({
  label,
  tone,
  title,
}: {
  label: string;
  tone: 'signal' | 'amber' | 'muted';
  title?: string;
}) {
  const colour = tone === 'signal' ? SIGNAL : tone === 'amber' ? AMBER : CREAM_MUTED;
  return (
    <span
      title={title}
      className="text-[10px] uppercase px-2.5 py-1 rounded-full whitespace-nowrap"
      style={{
        fontFamily: MONO_FONT,
        letterSpacing: '0.12em',
        color: colour,
        background: 'rgb(255 255 255 / 0.04)',
        border: `1px solid ${LINE2}`,
      }}
    >
      {label}
    </span>
  );
}

function formatTime(iso: string): string {
  const d = new Date(iso);
  const diffMs = Date.now() - d.getTime();
  const mins = Math.round(diffMs / 60_000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.round(hours / 24);
  if (days < 7) return `${days}d ago`;
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
}

function capitalise(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
